image: circleci/openjdk:8-jdk-browsers

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .m2/
    - target/

stages:
  - build
  - test    

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

build: &build
  stage: build
  script:
    - mvn clean compile -DskipTests -s ./settings.xml --batch-mode
  only:
    refs:
      - branches

build-tag:
  <<: *build
  artifacts:
    paths:
      - .m2/
    expire_in: 1h
  only:
    variables:
      - $CI_COMMIT_TAG =~ /^roberto-(stage|production)-.+/

test: &test
  stage: test
  script:
    - mvn test -s settings.xml
  only:
    refs:
      - branches

test-tag:
  <<: *test
  only:
    variables:
      - $CI_COMMIT_TAG =~ /^roberto-(stage|production)-.+/

   
