image: circleci/openjdk:11-jdk-browsers

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .m2/
    - target/

stages:
  - build
  - test  
  - sonar 
  - deploy 

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  APP_NAME: "roberto"
  CLUSTER_PRODUCTION: ""  

build: &build
  stage: build
  script:
    - mvn clean compile -DskipTests -s ./settings.xml --batch-mode
  only:
    refs:
      - branches

build-tag:
  <<: *build
  artifacts:
    paths:
      - .m2/
    expire_in: 1h
  only:
    variables:
      - $CI_COMMIT_TAG =~ /^roberto-(stage|production)-.+/

test: &test
  stage: test
  script:
    - mvn test -s settings.xml
  only:
    refs:
      - branches

test-tag:
  <<: *test
  only:
    variables:
      - $CI_COMMIT_TAG =~ /^roberto-(stage|production)-.+/

sonar: 
  stage: sonar
  script:
    - mvn sonar:sonar -Dsonar.host.url=$SONAR_HOST_URL -Dsonar.login=$SONAR_TOKEN
    - cat target/site/jacoco/index.html | grep -o '<tfoot>.*</tfoot>'
  coverage: "/Total.*?([0-9]{1,3})%/"
  only:
    refs:
      - master 

deploy-production:
  stage: deploy
  before_script:
    - mvn package -s settings.xml -DskipTests
  script:
    - ./deploy/deploy.sh $CLUSTER_PRODUCTION $APP_NAME
  only:
    refs:
      - tags
    variables:
      - $CI_COMMIT_TAG =~ /^production-.*/


   
